CREATE TABLE ETCCLEARRESULT
(
    CROPID Nullable(text),
    TOLLSECTIONID Nullable(text),
    TOLLINTERVALID text,
    TOLLSTATION Nullable(text),
    VEHICLETYPE Nullable(text),
    PAYTYPE Nullable(text),
    PAYCARDTYPE Nullable(text),
    PROVINCETYPE Nullable(text),
    LDATE Nullable(text),
    NATIONCLEARDATE Nullable(text),
    NATIONSPLITDATE Nullable(text),
    CLEARDATE Nullable(text),
    MULTIPROVINCE Nullable(text),
    MODIFYFLAG Nullable(text),
    ROADTYPE Nullable(text),
    BUSIBATCH Nullable(text),
    UNIONPAYTYPE Nullable(text),
    CLEARTYPE Nullable(text),
    ISSUERID Nullable(text),
    TOLLPROVINCEID Nullable(text),
    SERPROVINCEID Nullable(text),
    TOLLCROPID Nullable(text),
    SECTIONID Nullable(text),
    AMOUNT Nullable(Int32),
    DISCOUNTAMOUNT Nullable(Int32),
    CHARGEAMOUNT Nullable(Int32),
    REPORTFLAG Nullable(text),
    LASTTIME DateTime,
    EXTOLLSTATION Nullable(text)
) PRIMARY KEY (TOLLINTERVALID)

CREATE TABLE CASHCLEARRESULT
(
    CROPID Nullable(text),
    TOLLSECTIONID Nullable(text),
    TOLLINTERVALID text,
    TOLLSTATION Nullable(text),
    VEHICLETYPE Nullable(text),
    PAYTYPE Nullable(text),
    PAYCARDTYPE Nullable(text),
    PROVINCETYPE Nullable(text),
    LDATE Nullable(text),
    NATIONCLEARDATE Nullable(text),
    NATIONSPLITDATE Nullable(text),
    CLEARDATE Nullable(text),
    MULTIPROVINCE Nullable(text),
    MODIFYFLAG Nullable(text),
    ROADTYPE Nullable(text),
    BUSIBATCH Nullable(text),
    UNIONPAYTYPE Nullable(text),
    CLEARTYPE Nullable(text),
    ISSUERID Nullable(text),
    TOLLPROVINCEID Nullable(text),
    SERPROVINCEID Nullable(text),
    TOLLCROPID Nullable(text),
    SECTIONID Nullable(text),
    AMOUNT Nullable(Int32),
    DISCOUNTAMOUNT Nullable(Int32),
    CHARGEAMOUNT Nullable(Int32),
    REPORTFLAG Nullable(text),
    LASTTIME DateTime,
    REPORTDATE Nullable(text),
    EXTOLLSTATION Nullable(text)
) PRIMARY KEY (TOLLINTERVALID)

CREATE TABLE EXPANDCLEARRESULT
(
    CROPID text,
    VEHICLETYPE Nullable(text),
    PAYCARDTYPE Nullable(text),
    LDATE Nullable(text),
    NATIONCLEARDATE Nullable(text),
    CLEARDATE Nullable(text),
    BUSIBATCH Nullable(text),
    CLEARTYPE Nullable(text),
    ISSUERID Nullable(text),
    AMOUNT Nullable(Int32),
    REPORTFLAG Nullable(text),
    LASTTIME Nullable(DateTime),
    MODIFYFLAG Nullable(text)
) PRIMARY KEY (CROPID)
